#!/usr/bin/env sh

hw_create() {
    cd ./hardware || exit
    ./create
    cd ..
}

hw_build() {
    cd ./hardware || exit
    ./build
    cd ..
}

fw() {
    cd ./firmware || exit
    ./create
    cd ..
}

[ "$1" = "hw" ] && hw_create && exit
[ "$1" = "fw" ] && fw && exit
[ ! $# -eq 0 ] && echo "ERROR: unknown option $1, use hw or fw" && exit

start=$(date +%s)

hw_start=$(date +%s)
hw_create
hw_build
hw_end=$(date +%s)
hw_elapsed=$((hw_end-hw_start))

fw_start=$(date +%s)
fw
fw_end=$(date +%s)
fw_elapsed=$((fw_end-fw_start))

end=$(date +%s)
elapsed=$((end-start))

echo "================================================================================"
echo "CREATE STATS"
echo "hardware: $hw_elapsed seconds"
echo "firmware: $fw_elapsed seconds"
echo "hardware and firmware projects took $elapsed seconds"
echo "--------------------------------------------------------------------------------"
