#!/usr/bin/env sh
start=$(date +%s)
vivado -mode batch -source bitstream-program.tcl
end=$(date +%s)
elapsed=$((end-start))

echo "============================================="
echo "$0 took $elapsed seconds"
echo "---------------------------------------------"
