#!/usr/bin/env sh
start=$(date +%s)
vivado -mode batch -nojournal -notrace -source ./bitstream-create.tcl | tee "../$0.log" | grep -E 'ERROR:|WARNING:|Command:|bitstream'
end=$(date +%s)
elapsed=$((end-start))

echo "============================================="
echo "$0 took $elapsed seconds"
echo "---------------------------------------------"
