#!/usr/bin/env sh

# check version against version file and warn/halt on mismatch
VIVADO_VERSION=$(vivado -version | grep "vivado " | sed "s/^.*vivado //")
FILE_VIVADO_VERSION="$(cat ./vivado_version.txt)"
echo "$0 $FILE_VIVADO_VERSION"
[ "$FILE_VIVADO_VERSION" != "$VIVADO_VERSION" ] && echo "ERROR: hardware scripts created using $FILE_VIVADO_VERSION, but environment is $VIVADO_VERSION" && exit

cd ./vivado || exit

start=$(date +%s)

rm -rf ./*.log

vivado -mode batch -nojournal -notrace -source ../build-vivado.tcl | grep -E 'ERROR:|WARNING:|INFO:'

end=$(date +%s)
elapsed=$((end-start))

echo "============================================"
echo "build hardware project took $elapsed seconds"
echo "--------------------------------------------"
