#!/usr/bin/env sh

cd ./vivado || exit

start=$(date +%s)

rm -rf ./*.log

vivado -mode batch -nojournal -notrace -source ../build-vivado.tcl | grep -E 'ERROR:|WARNING:|INFO:'

end=$(date +%s)
elapsed=$((end-start))

echo "============================================"
echo "build hardware project took $elapsed seconds"
echo "--------------------------------------------"
