#!/usr/bin/env sh

[ -d "./vivado" ] && echo "directory vivado already exists - skipping hardware project creation" && exit
mkdir -p ./vivado # for log file

start=$(date +%s)
vivado -mode batch -nojournal -notrace -source ./create-vivado.tcl -log ./vivado/vivado.log | grep -E 'ERROR:|WARNING:|INFO:'
rm -rf .Xil
rm -rf NA
end=$(date +%s)
elapsed=$((end-start))

echo "============================================="
echo "create hardware project took $elapsed seconds"
echo "---------------------------------------------"
