#!/usr/bin/env sh

BUILD_ENVIRONMENT=build

OBJ_DIR="$PWD/$BUILD_ENVIRONMENT"
rm -f "$OBJ_DIR/sim"
rm -f "$OBJ_DIR/sim.exe"
./build-cmake
cd ../../hardware/src
[ -f $OBJ_DIR/sim ] && $OBJ_DIR/sim && exit
[ -f $OBJ_DIR/sim.exe ] && $OBJ_DIR/sim.exe && exit
