#!/usr/bin/env bash

unset xsct_cmd
command -v xsct &>/dev/null && export xsct_cmd="xsct"
command -v xsct.bat &>/dev/null && export xsct_cmd="xsct.bat"
[ -z ${xsct_cmd+x} ] && echo "ERROR: can't locate xsct.bat or xsct" && exit 1

start=$(date +%s)
cd vitis || exit
$xsct_cmd ../build-vitis.tcl
end=$(date +%s)
elapsed=$((end - start))

echo "============================================="
echo "build firmware project took $elapsed seconds"
echo "============================================="
